version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  groups:
    detekt:
      patterns:
      - "io.gitlab.arturbosch.detekt:*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
